name: deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Login Azure Registry
        uses: azure/docker-login@v1
        with:
          login-server: "mmmbacr.azurecr.io"
          username: "MMMBacr"
          password: ${{ secrets.PASSWORDAZURE }}

      - name: Docker pour azure
        run: |
          docker build . -t mmmbacr.azurecr.io/test:1
          docker push mmmbacr.azurecr.io/test:1
